final List<Map<String, String>> transactions = [
  {
    'svgPath': "assets/transactions/youtube.svg",
    'name': "Youtube",
    'time': "2:10 PM",
    'amount': "499",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/amazon.svg",
    'name': "Amazon",
    'time': "4:30 PM",
    'amount': "699",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/spotify.svg",
    'name': "Spotify",
    'time': "1:20 PM",
    'amount': "99",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/steam.svg",
    'name': "Steam",
    'time': "10:45 PM",
    'amount': "1399",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/youtube.svg",
    'name': "Youtube",
    'time': "1:00 PM",
    'amount': "599",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
];
