final List<Map<String, String>> transactions = [
  {
    'svgPath': "assets/transactions/upwork.svg",
    'name': "Upwork",
    'time': "11:20 PM",
    'amount': "5000",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/youtube.svg",
    'name': "Youtube",
    'time': "2:10 PM",
    'amount': "499",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/amazon.svg",
    'name': "Amazon",
    'time': "4:30 PM",
    'amount': "699",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/rent.svg",
    'name': "Rent",
    'time': "9:30 AM",
    'amount': "4500",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/fiverr.svg",
    'name': "Fiverr",
    'time': "3:55 PM",
    'amount': "9500",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/spotify.svg",
    'name': "Spotify",
    'time': "1:20 PM",
    'amount': "99",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/steam.svg",
    'name': "Steam",
    'time': "10:45 AM",
    'amount': "1399",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/binance.svg",
    'name': "Binance",
    'time': "12:32 PM",
    'amount': "7600",
    'transactionType': 'credit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/apple.svg",
    'name': "Apple Store",
    'time': "7:00 PM",
    'amount': "3999",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/uber.svg",
    'name': "Uber",
    'time': "8:30 AM",
    'amount': "199",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/dropbox.svg",
    'name': "Dropbox",
    'time': "11:15 AM",
    'amount': "749",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
  {
    'svgPath': "assets/transactions/kfc.svg",
    'name': "KFC",
    'time': "1:30 PM",
    'amount': "649",
    'transactionType': 'debit',
    'debitIcon': 'assets/icons/transfer.svg',
    'creditIcon': 'assets/icons/request.svg',
  },
];
